# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T17:49:20+00:00



import argparse
import json
import os
from typing import *

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity
from pydantic import constr

app = MCPProxy(
    contact={
        'email': 'info@calorieninjas.com',
        'name': 'CalorieNinjas team',
        'url': 'www.calorieninjas.com',
    },
    description='Natural language nutrition API to extract nutrition data from any text.',
    license={
        'name': 'Apache 2.0',
        'url': 'http://www.apache.org/licenses/LICENSE-2.0.html',
    },
    termsOfService='www.calorieninjas.com/tos',
    title='CalorieNinjas',
    version='1.0.0',
    servers=[
        {'description': 'CalorieNinjas API server', 'url': 'api.calorieninjas.com'}
    ],
)


@app.get(
    '/v1/nutrition',
    description=""" Returns a list of food item nutrition facts extracted from an input string containing food and beverage words.  """,
    tags=['nutrition_information'],
    security=[
        APIKeyHeader(name="api_key"),
    ],
)
def get_v1_nutrition(query: constr(min_length=0, max_length=1500)):
    """
    Get nutrition text for an input string containing food and beverage words.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
